# Generated by Django 4.2.30 on 2026-05-03 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('academic_pressure', models.FloatField()),
                ('sleep_duration', models.CharField(choices=[('Less than 5 hours', 'Less than 5 hours'), ('5-6 hours', '5-6 hours'), ('7-8 hours', '7-8 hours'), ('More than 8 hours', 'More than 8 hours')], max_length=30)),
                ('cgpa', models.FloatField()),
                ('study_satisfaction', models.FloatField()),
                ('work_pressure', models.FloatField()),
                ('prediction', models.CharField(choices=[('Low', 'Low Risk'), ('Medium', 'Medium Risk'), ('High', 'High Risk')], max_length=10)),
                ('prediction_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Prediction Result',
                'verbose_name_plural': 'Prediction Results',
                'ordering': ['-created_at'],
            },
        ),
    ]
